name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    node:
        name: Node ${{ matrix.node }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ["16.x", "18.x", "20.x"]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}

            - name: Install Dependencies
              run: npm ci

            - name: Run Lint
              run: npm run lint

            - name: Run Build
              run: npm run build

            - name: Coverage Report
              uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                annotations: none
