name: Publish and release

on:
    push:
        branches: [main]
jobs:
    publish:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ["16.x"]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
                  registry-url: https://registry.npmjs.org
            - name: Install Dependencies
              run: npm install

            - name: Run Build
              run: npm run build

            - uses: changesets/action@v1
              with:
                  title: Release
                  publish: npm run build && npm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
